"use client";

import { useState, FormEvent } from "react";
import { useRouter } from "next/navigation";

type Item = {
  id: number;
  code: string;
  label: string;
  targetPath: string;
  scans: number;
  lastScannedAt: string | null;
  url: string;
  svg: string; // generated by our own encoder from the matrix only
};

export default function QrLinksPanel({ links }: { links: Item[] }) {
  const router = useRouter();
  const [label, setLabel] = useState("");
  const [targetPath, setTargetPath] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function create(e: FormEvent) {
    e.preventDefault();
    setError(null);
    setBusy(true);
    try {
      const res = await fetch("/api/admin/qr-links", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ label, targetPath }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "Couldn't create the link.");
        return;
      }
      setLabel("");
      setTargetPath("");
      router.refresh();
    } catch {
      setError("Couldn't create the link.");
    } finally {
      setBusy(false);
    }
  }

  async function remove(item: Item) {
    if (!confirm(`Retire "${item.label}"? Codes already printed will stop working.`)) return;
    const res = await fetch(`/api/admin/qr-links/${item.id}`, { method: "DELETE" });
    if (res.ok) router.refresh();
    else setError("Couldn't delete that link.");
  }

  return (
    <>
      <form onSubmit={create} style={{ marginBottom: 24, maxWidth: 560 }}>
        {error && <p role="alert" style={{ color: "#c0392b" }}>{error}</p>}
        <div className="form-group">
          <label>Label (for your own reference)</label>
          <input className="form-control" required maxLength={120} value={label} onChange={(e) => setLabel(e.target.value)} placeholder="e.g. Oct 12 edition, page 3, Joe's Tacos ad" />
        </div>
        <div className="form-group">
          <label>Page it opens (a path on this site)</label>
          <input className="form-control" required maxLength={200} value={targetPath} onChange={(e) => setTargetPath(e.target.value)} placeholder="/deals" />
        </div>
        <button className="btn btn-primary" type="submit" disabled={busy}>{busy ? "Creating…" : "Create QR code"}</button>
      </form>

      {links.length === 0 ? (
        <p style={{ color: "#888" }}>No QR codes yet.</p>
      ) : (
        <table className="table">
          <thead>
            <tr><th>QR</th><th>Label</th><th>Opens</th><th>Visits</th><th /></tr>
          </thead>
          <tbody>
            {links.map((l) => (
              <tr key={l.id}>
                <td style={{ width: 120 }} dangerouslySetInnerHTML={{ __html: l.svg }} />
                <td>
                  <strong>{l.label}</strong>
                  <div style={{ fontSize: 12, color: "#888", wordBreak: "break-all" }}>{l.url}</div>
                </td>
                <td>{l.targetPath}</td>
                <td>
                  {l.scans}
                  {l.lastScannedAt && <div style={{ fontSize: 12, color: "#888" }}>last {l.lastScannedAt} UTC</div>}
                </td>
                <td style={{ whiteSpace: "nowrap" }}>
                  <a className="btn btn-default btn-sm" href={`/api/admin/qr-links/${l.id}/svg`}>Download SVG</a>{" "}
                  <button className="btn btn-danger btn-sm" onClick={() => remove(l)}>Delete</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
      <p style={{ color: "#888", fontSize: 13 }}>
        &ldquo;Visits&rdquo; counts every time the short link is opened, including repeat visits and link previews, so
        treat it as a rough measure rather than an exact count of readers.
      </p>
    </>
  );
}
